name: Build and Publish Docker Container

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker login # TODO: we need to get the pandare account on dockerhub or push to github
      run: docker login -u fasano -p ${{secrets.fasano_dockerhub}}

    - name: Build Bionic container
      run:  cd ${GITHUB_WORKSPACE}/panda/docker && docker build . -f Dockerfile_18_04 -t fasano/panda_bionic:latest;
            docker tag  fasano/panda_bionic:latest fasano/panda_bionic:${GITHUB_SHA};
            docker push fasano/panda_bionic:${GITHUB_SHA};
            docker push fasano/panda_bionic:latest
    - name: Build Xenial container
      run:  cd ${GITHUB_WORKSPACE}/panda/docker && docker build . -f Dockerfile_16_04 -t fasano/panda_xenial:latest;
            docker tag  fasano/panda_xenial:latest fasano/panda_xenial:${GITHUB_SHA};
            docker push fasano/panda_xenial:${GITHUB_SHA};
            docker push fasano/panda_xenial:latest
