name: Docker Build - Clean
# For PRs to master, build from a clean image

# Clone latest pre-built docker container
# Checkout the relevant branch
# Run make clean && make in the build directory

# Because this runs on PR actions, $GITHUB_SHA is set to some weird branch
# so we pass $GITHUB_REF
#
on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Fetch pre-built bionic docker container
      run: docker pull pandare/panda:latest

    - name: Download docker/update.sh script from this commit
      run: wget "https://raw.githubusercontent.com/panda-re/panda/${GITHUB_SHA}/panda/docker/update.sh"

    - name: Inside container run update.sh to fetch this commit, make a *clean* build
      run: docker run --rm -v $(pwd)/update.sh:/update.sh pandare/panda bash /update.sh "$GITHUB_REF" clean
