# Run directly with act - standard repo-name guards are disabled and runs without self-hosted.
# See .github/workflows/README.md for more details
#
# Note that this action never runs automatically

name: Local

jobs:
  local_build_container:
    runs-on: panda-arc
    steps:
    - uses: actions/checkout@v2 # Clones to $GITHUB_WORKSPACE. NOTE: this requires git > 2.18 (not on ubuntu 18.04 by default) to get .git directory

    - name: Build docker container from project root
      run: echo $GITHUB_WORKSPACE; cd $GITHUB_WORKSPACE && DOCKER_BUILDKIT=1 docker build --progress=plain --target developer -t panda_local:${{ github.sha }} .

    - name: Minimal test of built container # Just test to see if one of our binaries is built
      run: docker run --rm "panda_local:${{ github.sha }}" /bin/bash -c 'exit $(/panda/build/arm-softmmu/panda-system-arm -help | grep -q "usage. panda-system-arm")'
